
.PHONY: build
build:
    ./app/gradlew build

.PHONY: run-dist
run-dist:
    ./app/build/install/app/bin/app

.PHONY: checkstyle
checkstyle:
    ./app/gradlew checkstyleMain

.PHONY: clean
clean:
    ./app/gradlew clean